[functions]
  node_bundler = "esbuild"

# update every 20 minutes
[functions."updater-scheduled"]
schedule = "0/20 * * * *"

# update every 10 minutes
[functions."snallabot-event-publisher"]
schedule = "0 * * * *"

# update every day
[functions."snallabot-gc-scheduled"]
schedule = "*/5 * * * *"