[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/leagueteams"
  to = "https://nallapareddy.netlify.app/.netlify/functions/exporter?api=leagueteams&league=:leagueId&username=:username"
  status = 200
  force = false

[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/standings"
  to = "https://nallapareddy.netlify.app/.netlify/functions/exporter?api=standings&league=:leagueId&username=:username"
  status = 200
  force = false

[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/week/:weekType/:weekNumber/:dataType"
  to = "/.netlify/functions/exporter?api=week&league=:leagueId&username=:username&weekType=:weekType&weekNumber=:weekNumber&datatype=:dataType"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"
