[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/leagueteams"
  to = "/.netlify/functions/exporter?api=leagueteams&username=:username&league=:leagueId"
  status = 301
  force = false

[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/standings"
  to = "/.netlify/functions/exporter?api=standings&username=:username&league=:leagueId"
  status = 301
  force = false

[[redirects]]
  from = "/madden/exporter/:username/:platform/:leagueId/week/:weekType/:weekNumber/:dataType"
  to = "/.netlify/functions/exporter?api=week&username=:username&league=:leagueId&weekType=:weekType&weekNumber=:weekNumber&datatype=:dataType"
  status = 301
  force = false

